export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Dashboard} from "./Dashboard"
export {default as AddProject} from "./AddProject"
export {default as Project} from "./Project"